services:
  pansou:
    image: ghcr.io/granthuang999/pansou-web:latest
    container_name: pansou-app
    ports:
      - "127.0.0.1:8888:80"   # 容器只对本机开放，不直接暴露公网 80
    environment:
      - DOMAIN=pansou.futuremedia.work
      - PANSOU_PORT=8888
      - PANSOU_HOST=127.0.0.1
    volumes:
      - /opt/pansou/data:/app/data
      - /opt/pansou/logs:/app/logs
    restart: unless-stopped
